-- =====================================================================
-- 03 - PERBAIKAN SKEMA
-- Jalankan setelah 01 dan 02. Aman dijalankan ulang.
-- Sebaiknya unduh cadangan data dulu (Database > Backups, atau ekspor CSV).
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. riwayat_kuis.id harus terisi otomatis
--    Di struktur yang dikirim, kolom ini "bigint not null" tanpa default,
--    sehingga insert dari aplikasi (yang tidak mengirim id) akan gagal.
-- ---------------------------------------------------------------------
do $$
begin
    if not exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'riwayat_kuis' and column_name = 'id'
          and (is_identity = 'YES' or column_default is not null)
    ) then
        alter table public.riwayat_kuis alter column id add generated by default as identity;
        perform setval(
            pg_get_serial_sequence('public.riwayat_kuis', 'id'),
            coalesce((select max(id) from public.riwayat_kuis), 0) + 1,
            false
        );
    end if;
end $$;


-- ---------------------------------------------------------------------
-- 2. Perbaiki data kota yang salah tersimpan
--    Formulir lama menampilkan "Semarang" tetapi menyimpan "Surabaya".
--    Semua "Surabaya" di data ini sebenarnya adalah responden Semarang.
-- ---------------------------------------------------------------------
update public.profiles set kota = 'Semarang' where kota = 'Surabaya';

alter table public.profiles drop constraint if exists profiles_kota_check;
alter table public.profiles
    add constraint profiles_kota_check
    check (kota is null or kota in ('Ternate', 'Palembang', 'Semarang')) not valid;
-- Jika nanti ada kota baru, jalankan ulang dua baris di atas dengan daftar kota yang baru.


-- ---------------------------------------------------------------------
-- 3. total_poin tidak boleh kosong, tanggal lahir harus masuk akal
-- ---------------------------------------------------------------------
update public.profiles set total_poin = 0 where total_poin is null;
alter table public.profiles alter column total_poin set default 0;
alter table public.profiles alter column total_poin set not null;

alter table public.profiles drop constraint if exists profiles_tanggal_lahir_check;
alter table public.profiles
    add constraint profiles_tanggal_lahir_check
    check (tanggal_lahir is null or tanggal_lahir >= date '1940-01-01') not valid;


-- ---------------------------------------------------------------------
-- 4. buku.id_kuis_terkait: text -> uuid yang benar-benar menunjuk ke buku
-- ---------------------------------------------------------------------
do $$
begin
    if (select data_type from information_schema.columns
        where table_schema = 'public' and table_name = 'buku' and column_name = 'id_kuis_terkait') = 'text' then

        -- Kosongkan nilai yang bukan uuid atau menunjuk ke buku yang sudah tidak ada
        update public.buku b set id_kuis_terkait = null
        where id_kuis_terkait is not null
          and (
              trim(id_kuis_terkait) !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
              or not exists (select 1 from public.buku x where x.id::text = trim(b.id_kuis_terkait))
          );

        alter table public.buku
            alter column id_kuis_terkait type uuid using nullif(trim(id_kuis_terkait), '')::uuid;
    end if;
end $$;

alter table public.buku drop constraint if exists buku_id_kuis_terkait_fkey;
alter table public.buku
    add constraint buku_id_kuis_terkait_fkey
    foreign key (id_kuis_terkait) references public.buku (id) on delete set null;


-- ---------------------------------------------------------------------
-- 5. Indeks agar analitik tetap cepat saat responden bertambah
-- ---------------------------------------------------------------------
create index if not exists riwayat_kuis_id_user_idx    on public.riwayat_kuis (id_user);
create index if not exists riwayat_kuis_id_buku_idx    on public.riwayat_kuis (id_buku);
create index if not exists riwayat_kuis_created_at_idx on public.riwayat_kuis (created_at);
create index if not exists kuis_id_buku_idx            on public.kuis (id_buku);


-- ---------------------------------------------------------------------
-- 6. Profil otomatis terisi dari data pendaftaran
--    Aplikasi mengirim nama, jenis kelamin, kategori, kota, dan tanggal
--    lahir sebagai metadata saat daftar. Trigger ini menyalinnya ke
--    profiles, sehingga data tetap tersimpan walaupun "Confirm email"
--    aktif (saat itu aplikasi belum punya sesi login untuk menulis sendiri).
--    Nama trigger diawali "zz_" agar berjalan SETELAH trigger lama Anda,
--    dan memakai ON CONFLICT sehingga tidak bentrok dengannya.
-- ---------------------------------------------------------------------
create or replace function public.isi_profil_dari_metadata()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    m jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
    tgl date := case
        when (m->>'tanggal_lahir') ~ '^\d{4}-\d{2}-\d{2}$' then (m->>'tanggal_lahir')::date
        else null
    end;
begin
    insert into public.profiles (id, nama_lengkap, jenis_kelamin, kategori, kota, tanggal_lahir, total_poin)
    values (
        new.id,
        coalesce(nullif(trim(m->>'nama_lengkap'), ''), split_part(new.email, '@', 1)),
        case when m->>'jenis_kelamin' in ('Laki-laki', 'Perempuan') then m->>'jenis_kelamin' end,
        case when m->>'kategori' in ('Pelajar', 'Mahasiswa', 'Umum') then m->>'kategori' end,
        case when m->>'kota' in ('Ternate', 'Palembang', 'Semarang') then m->>'kota' end,
        tgl,
        0
    )
    on conflict (id) do update set
        nama_lengkap  = coalesce(nullif(trim(m->>'nama_lengkap'), ''), public.profiles.nama_lengkap),
        jenis_kelamin = coalesce(excluded.jenis_kelamin, public.profiles.jenis_kelamin),
        kategori      = coalesce(excluded.kategori, public.profiles.kategori),
        kota          = coalesce(excluded.kota, public.profiles.kota),
        tanggal_lahir = coalesce(excluded.tanggal_lahir, public.profiles.tanggal_lahir);
    return new;
end;
$$;

drop trigger if exists zz_isi_profil_dari_metadata on auth.users;
create trigger zz_isi_profil_dari_metadata
    after insert on auth.users
    for each row execute function public.isi_profil_dari_metadata();


-- ---------------------------------------------------------------------
-- Catatan: relasi riwayat_kuis -> buku sengaja TIDAK diberi ON DELETE CASCADE.
-- Modul yang sudah punya jawaban responden tidak bisa terhapus, sehingga
-- data penelitian aman. Untuk menyembunyikan modul, matikan is_active saja.
-- ---------------------------------------------------------------------
